use_frameworks!

platform :ios, '10.0'

target 'BugBattle_Example' do
  pod 'BugBattle', :path => '../'
  pod 'Alamofire', '~> 5.2'
  pod 'AFNetworking', '~> 4.0'
  
  target 'BugBattle_Tests' do
    inherit! :search_paths
    
  end
end
